version: 0.2

phases:
  build:
    commands:
      - sam build

  post_build:
    commands:
      - sam package --s3-bucket $S3_BUCKET --output-template-file package.yml

artifacts:
  files:
    - package.yml