AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

#################################
# PARAMETERS
#################################
Parameters:
  ProjectName:
    Type: String
    Default: contact

  Environment:
    Type: String
    Default: dev

  UserId:
    Type: String
    Description: Identificador único por estudiante

  Stage:
    Type: String
    Default: prod

#################################
# GLOBALS
#################################
Globals:
  Function:
    Handler: index.handler
    Runtime: nodejs20.x
    Timeout: 300
    MemorySize: 1024
    Tags:
      SYSTEM: !Ref ProjectName
      ENV: !Ref Environment
      OWNER: !Ref UserId

#################################
# VARIABLES DERIVADAS
#################################
Mappings:
  RegionMap:
    us-east-1:
      RegionShortName: ''
    us-west-1:
      RegionShortName: 'uw1'

#################################
# RESOURCES
#################################
Resources:

  #################################
  # DynamoDB
  #################################
  ContactDynamoDB:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: !Sub "${ProjectName}-${UserId}-${Environment}"
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  #################################
  # API
  #################################
  ContactApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "${ProjectName}-api-${UserId}"
      StageName: !Ref Stage
      EndpointConfiguration: REGIONAL

  #################################
  # IAM ROLE BASE
  #################################
  BaseLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ProjectName}-${UserId}-lambda-role"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  #################################
  # FUNCTIONS
  #################################

  ContactCreateLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-create-${UserId}"
      CodeUri: build/create
      Role: !GetAtt BaseLambdaRole.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref ContactDynamoDB
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ContactApi
            Path: /
            Method: POST

  ContactGetLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-get-${UserId}"
      CodeUri: build/get
      Role: !GetAtt BaseLambdaRole.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref ContactDynamoDB
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ContactApi
            Path: /{email}
            Method: GET

  ContactDeleteLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-delete-${UserId}"
      CodeUri: build/delete
      Role: !GetAtt BaseLambdaRole.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref ContactDynamoDB
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ContactApi
            Path: /{email}
            Method: DELETE

  ContactUpdateLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-update-${UserId}"
      CodeUri: build/update
      Role: !GetAtt BaseLambdaRole.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref ContactDynamoDB
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ContactApi
            Path: /{email}
            Method: PUT